<a href="https://colab.research.google.com/github/Deadpoets888/Pytorch/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00 pytorch

In [ ]:
!nvidia-smi


Fri Mar 28 12:16:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


#Introduction to TENSORS

In [ ]:
#scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

8

In [ ]:
#vector
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[8, 9], [1, 2]])
MATRIX

tensor([[8, 9],
        [1, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([8, 9])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 2], [2, 4, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 2],
         [2, 4, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tenors full of random numbers and then adjust those random numbers to better represent the data.


`start with random numbers -> look at data -> update random numbers ->look at data -> update random numbers.`

In [ ]:
# create a random number of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9657, 0.3587, 0.9184, 0.1392],
        [0.8833, 0.0379, 0.4384, 0.7231],
        [0.9276, 0.3326, 0.3236, 0.7575]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channels. height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###Zeroes and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
  # Create a tensor of all ones
  ones = torch.ones(size = (3, 4))
  ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
zero_to_thousand = torch.arange(start = 0, end = 1000, step = 77)
zero_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
zeroes1 = torch.zeros_like(input = zero_to_thousand)
zeroes1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes
Note : tensor datatypes is one of the 3 big errors you'll run into with pytorch & deepLearning

1. Tensors is not in right datatype
2. Tensors is not in right shape
3. Tensors is not in right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 5.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 5., 9.])

In [ ]:
float_32_tensor.dtype #float32 is bydefault datatype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0, 5.0, 9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 5., 9.], dtype=torch.float16)

In [8]:
float_32_tensor_1 = torch.tensor([3.0, 3.1, 5.1],
                                 dtype= None, #what datatype is the tensor (e.g. float32 or float16)
                                 device = None, # what device is your tensor on # whether or not to track gradiesnts with this tensors operations
                                 requires_grad = False)
float_32_tensor_1

tensor([3.0000, 3.1000, 5.1000])

In [6]:
float_32_tensor_1.dtype

torch.float32

In [7]:
float_16_tensor_1 = float_32_tensor_1.type(torch.float16)
float_16_tensor_1

tensor([3.0000, 3.0996, 5.1016], dtype=torch.float16)

In [10]:
k = float_16_tensor_1 * float_32_tensor_1
k

tensor([ 9.0000,  9.6088, 26.0180])

In [11]:
k.dtype

torch.float32

In [14]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [17]:
m = int_32_tensor * float_32_tensor_1
m

tensor([ 9.0000, 18.6000, 45.9000])

In [18]:
m.dtype #When you multiply an int32 tensor with a float32 tensor, most computing frameworks (such as NumPy, TensorFlow, or PyTorch) automatically promote the lower precision type (int32) to the higher precision type (float32).

torch.float32