<a href="https://colab.research.google.com/github/Deadpoets888/Pytorch/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00 pytorch

In [ ]:
!nvidia-smi


Fri Mar 28 12:16:09 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


#Introduction to TENSORS

In [ ]:
#scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

8

In [ ]:
#vector
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[8, 9], [1, 2]])
MATRIX

tensor([[8, 9],
        [1, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([8, 9])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 2], [2, 4, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 2],
         [2, 4, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tenors full of random numbers and then adjust those random numbers to better represent the data.


`start with random numbers -> look at data -> update random numbers ->look at data -> update random numbers.`

In [ ]:
# create a random number of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9657, 0.3587, 0.9184, 0.1392],
        [0.8833, 0.0379, 0.4384, 0.7231],
        [0.9276, 0.3326, 0.3236, 0.7575]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channels. height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###Zeroes and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
  # Create a tensor of all ones
  ones = torch.ones(size = (3, 4))
  ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
zero_to_thousand = torch.arange(start = 0, end = 1000, step = 77)
zero_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
zeroes1 = torch.zeros_like(input = zero_to_thousand)
zeroes1

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes
Note : tensor datatypes is one of the 3 big errors you'll run into with pytorch & deepLearning

1. Tensors is not in right datatype
2. Tensors is not in right shape
3. Tensors is not in right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 5.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 5., 9.])

In [ ]:
float_32_tensor.dtype #float32 is bydefault datatype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0, 5.0, 9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 5., 9.], dtype=torch.float16)

In [8]:
float_32_tensor_1 = torch.tensor([3.0, 3.1, 5.1],
                                 dtype= None, #what datatype is the tensor (e.g. float32 or float16)
                                 device = None, # what device is your tensor on # whether or not to track gradiesnts with this tensors operations
                                 requires_grad = False)
float_32_tensor_1

tensor([3.0000, 3.1000, 5.1000])

In [6]:
float_32_tensor_1.dtype

torch.float32

In [7]:
float_16_tensor_1 = float_32_tensor_1.type(torch.float16)
float_16_tensor_1

tensor([3.0000, 3.0996, 5.1016], dtype=torch.float16)

In [10]:
k = float_16_tensor_1 * float_32_tensor_1
k

tensor([ 9.0000,  9.6088, 26.0180])

In [11]:
k.dtype

torch.float32

In [14]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [17]:
m = int_32_tensor * float_32_tensor_1
m

tensor([ 9.0000, 18.6000, 45.9000])

In [18]:
m.dtype #When you multiply an int32 tensor with a float32 tensor, most computing frameworks (such as NumPy, TensorFlow, or PyTorch) automatically promote the lower precision type (int32) to the higher precision type (float32).

torch.float32

### Getting information from Tensors

In [19]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2606, 0.9131, 0.9234, 0.0234],
        [0.3382, 0.8276, 0.0231, 0.6512],
        [0.5071, 0.3621, 0.0833, 0.9279]])

In [20]:
#find out details about some tensor
print(some_tensor)
print("datatype of some tensor:", some_tensor.dtype)
print("shape of some tensor:", some_tensor.shape)
print("device of some tensor:", some_tensor.device)

tensor([[0.2606, 0.9131, 0.9234, 0.0234],
        [0.3382, 0.8276, 0.0231, 0.6512],
        [0.5071, 0.3621, 0.0833, 0.9279]])
datatype of some tensor: torch.float32
shape of some tensor: torch.Size([3, 4])
device of some tensor: cpu


###Manipulating tensors

tensors operations include

*Addition

*Subtraction

*Multiplication(element-wise)

*Division

*Matrix multiplication

In [30]:
tensor = torch.tensor([1, 3, 5])
tensor + 10

tensor([11, 13, 15])

In [31]:
tensor * 10

tensor([10, 30, 50])

In [32]:
tensor

tensor([1, 3, 5])

In [33]:
tensor = tensor - 10
tensor

tensor([-9, -7, -5])

In [34]:
tensor

tensor([-9, -7, -5])

In [35]:
#try out pytorch in-built function
torch.mul(tensor, 10)


tensor([-90, -70, -50])

### Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:

1. element wise Multiplication
2. Matrix multiplication

In [37]:
tensor

tensor([-9, -7, -5])

In [41]:
#element wise
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([-9, -7, -5]) * tensor([-9, -7, -5])
Equals: tensor([81, 49, 25])


In [40]:
#matrix multiplication
torch.matmul(tensor, tensor) # U can use mm instead of matmul

tensor(155)

In [43]:
#checking time
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(155)
CPU times: user 763 µs, sys: 0 ns, total: 763 µs
Wall time: 1.64 ms


In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 773 µs, sys: 0 ns, total: 773 µs
Wall time: 625 µs


tensor(155)

In [ ]:
# to change the shape of matrix you need to use Transpose (matrix).T

###Finding the min, max, mean, sum, etc(tensor aggregation)

In [45]:
#create tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
#Find the min
torch.min(x)

tensor(0)

In [48]:
#Find the mx
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# find mean - torch.mean() function requires a tensor of float or complex datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##FInding the positional min and max

In [57]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
#finding the position in tensor that has the minimum value with agrmin()
x.argmin()

tensor(0)

In [60]:
x.argmax()

tensor(9)

###Reshaping, stacking, squeezing and unsqueezing tensors

*Reshaping - reshapes an input tensor to a defined shape

*View - Return a view of an input tensor of certain shape but keep the same memory as the  original tensor

*Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)

*Squeeze - removes all 1 dimension from a tensor

*Unsqueeze - add a 1 dimension to a target tensor

*Permute - Return a view of the input with dimension premuted(swapped) in a certain way

In [61]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
#reshaping
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
y_reshaped = y.reshape(9, 1)
y_reshaped, y_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [68]:
#change the ciew
z = y.view(1, 9)
z, y.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]))

In [71]:
#changing z changes y(because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [76]:
#stacking tensors on top of each other
x_stacked = torch.stack([y, y, y, y], dim = 0) #in vstack we use dimenstions equal to 0
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
x_stacked = torch.stack([y, y, y, y], dim = 1) # in hstack we use dimesions equal to 1
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [79]:
# torch.squeeze() - removes all single dimensions from a target
y_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [82]:
Y_rehsaped_1 = y_reshaped.T
Y_rehsaped_1

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [83]:
Y_rehsaped_1.shape

torch.Size([1, 9])

In [84]:
Y_rehsaped_1.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
Y_rehsaped_1.squeeze().shape


torch.Size([9])

In [89]:
# torch.unsqueeze -  adds a single dimension to a target tensor at a specific dimension
x_unsqueezed1 = Y_rehsaped_1.squeeze().unsqueeze(dim=0)
x_unsqueezed1

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [91]:
x_unsqueezed1.shape

torch.Size([1, 9])

In [90]:
x_unsqueezed2 = Y_rehsaped_1.squeeze().unsqueeze(dim=1)
x_unsqueezed2

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [92]:
x_unsqueezed2.shape

torch.Size([9, 1])

In [96]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
s = torch.rand(224, 224, 3)
s_permuted = s.permute(2, 0, 1)
s.shape, s_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [99]:
#permute returns different view of original tensor, and view in tensor shares memory in original tensor
s[0, 0, 0] = 34324
s[0, 0, 0], s_permuted[0, 0, 0]

(tensor(34324.), tensor(34324.))

###Indexing(selecting data from tensors)

Indexing with pytorch is similar to indexing with NumPy


In [100]:
#create a tensor
x =  torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [101]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [102]:
x[0][0]

tensor([1, 2, 3])

In [103]:
x[0][0][0]

tensor(1)

In [105]:
x[0][1][1]

tensor(5)

In [106]:
x[:, 0] # : means "select all elements along this axis" (so the first axis is not removed).

#0 means "select the first row from each of those elements."
# : -> doesn't remove(reduce) dimensions, that's why we get result with different dimensions with x[0][0] and x[:, 0]

tensor([[1, 2, 3]])

In [110]:
x[:, :, 1]
#First : → Selects all elements in the first axis (batch dimension).

#Second : → Selects all rows.

#1 in the third axis → Picks the second column (index 1) from each row.

tensor([[2, 5, 8]])

In [113]:
x[0, 1, 1]

tensor(5)

In [114]:
x[:, 1, 1] #1 dimension got preserved

tensor([5])

In [116]:
x[0, 0, :]

tensor([1, 2, 3])